// This enum should mirror the one on your backend
export enum AuditLogAction {
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGOUT = 'USER_LOGOUT',
  USER_ROLE_UPDATED = 'USER_ROLE_UPDATED',
  SETTINGS_UPDATED = 'SETTINGS_UPDATED',
  PRODUCT_CREATED = 'PRODUCT_CREATED',
  PRODUCT_UPDATED = 'PRODUCT_UPDATED',
  PRODUCT_DELETED = 'PRODUCT_DELETED',
  INVENTORY_ADJUSTED_MANUALLY = 'INVENTORY_ADJUSTED_MANUALLY',
  ORDER_CREATED = 'ORDER_CREATED',
  ORDER_STATUS_CHANGED = 'ORDER_STATUS_CHANGED',
  ORDER_RETURNED = 'ORDER_RETURNED',
  PO_CREATED = 'PO_CREATED',
  PO_STATUS_CHANGED = 'PO_STATUS_CHANGED',
  PO_ITEMS_RECEIVED = 'PO_ITEMS_RECEIVED',
}