
export enum TimeSeriesMetric {
  REVENUE_EX_TAX = 'REVENUE_EX_TAX',
  TOTAL_COST = 'TOTAL_COST',
  GROSS_PROFIT = 'GROSS_PROFIT',
  NET_PROFIT = 'NET_PROFIT',
  TOTAL_DISCOUNTS = 'TOTAL_DISCOUNTS',
  TOTAL_TAX = 'TOTAL_TAX',
}